version: '3'
services:
  opensearch-node:
    restart: always
    build:
      context: ./opensearch
    container_name: opensearch-node
    environment:
      cluster.name: opensearch-cluster
      node.name: opensearch-node
      discovery.seed_hosts: opensearch-node
      # cluster.initial_master_nodes: opensearch-node
      bootstrap.memory_lock: "true" # along with the memlock settings below, disables swapping
      OPENSEARCH_JAVA_OPTS: "-Xms1g -Xmx1g"
      DISABLE_INSTALL_DEMO_CONFIG: "true"
      DISABLE_SECURITY_PLUGIN: "true"
      discovery.type: single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
      # - ./opensearch/opensearch-node1/config/opensearch.yml:/usr/share/opensearch/config/opensearch.yml:ro,Z
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - opensearch-net
  opensearch-dashboards:
    restart: always
    build:
      context: ./opensearch-dashboards
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"
      DISABLE_INSTALL_DEMO_CONFIG: "true"
      OPENSEARCH_HOSTS: '["http://opensearch-node:9200"]'
    # volumes:
    #   - ./opensearch-dashboards/config/opensearch_dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml:ro,Z
    networks:
      - opensearch-net
    depends_on:
      - opensearch-node
  logstash:
    build:
      context: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro,Z
    ports:
      - "5044:5044"
      # - "5000:5000"
    environment:
      LS_JAVA_OPTS: -Xmx1g -Xms1g
      LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
    networks:
      - opensearch-net
    depends_on:
      - opensearch-node
  filebeat:
    build:
      context: filebeat/
      args:
        FILEBEAT_VERSION: ${FILEBEAT_VERSION}
    # windows DACL
    entrypoint: "filebeat -e -strict.perms=false"
    volumes:
      - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml:rw,Z
      - filebeat:/usr/share/filebeat
      - application:/usr/share/application:rw,Z
      - nginx:/usr/share/nginx:rw,Z
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}
    networks: 
      - opensearch-net
    depends_on:
      - logstash
  application:
    build:
      context: application/
    volumes:
      - application:/usr/share/application:rw,Z
    expose:
      - "8080"
    networks:
      - opensearch-net
    depends_on:
      - filebeat
    environment:
      TZ: Asia/Seoul
  nginx:
    build:
      context: nginx/
    volumes:
      - nginx:/usr/share/nginx:rw,Z
      - ./nginx/static:/usr/share/nginx/html
      - ./nginx/conf:/etc/nginx/
    ports:
      - "80:80"
    networks:
      - opensearch-net
    depends_on:
      - application
    environment:
      TZ: Asia/Seoul
volumes:
  opensearch-data1:
  application:
  filebeat:
  nginx:

networks:
  opensearch-net:
