FROM nginx:latest

#COPY static/index.html /usr/share/nginx/html
#COPY conf/nginx.conf /etc/nginx/nginx.conf
RUN mkdir -p /usr/share/nginx/application/access
RUN mkdir -p /usr/share/nginx/application/error